set -g base-index 1
set -g pane-base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g mouse on
set -g renumber-windows on
set -g set-clipboard on
set -g status-interval 2
set -g status-left-length 200
set -g status-position bottom
set -g status-right ''
set -g focus-events on
set -g window-size latest

setw -g mode-keys vi

set-option default-terminal "tmux-256color"
set-option -g terminal-overrides ',xterm-256:RGB'
set-option -g status-style bg=default

unbind [
unbind &

bind-key -n § copy-mode
bind-key -T copy-mode-vi § send-keys -X cancel

bind h select-pane  -L -Z
bind j select-pane  -D -Z
bind k select-pane  -U -Z
bind l select-pane  -R -Z
bind & kill-window

# Vi bindings for resizing panes
bind H   resize-pane  -L
bind J   resize-pane  -D
bind K   resize-pane  -U
bind L   resize-pane  -R

# macOS-like pane splits
bind n split-window -h -c "#{pane_current_path}"
bind N split-window -v -c "#{pane_current_path}"

# copy mode closer to macOS
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
